### ISSUE TITLE
Newline after every event

### ISSUE THREAD

**Issue by MJohnson459** [thoren-d/tracing-chrome#2]
When I turn this Subscriber on the trace file generated can be huge in relatively little time (1GB per minute almost). Trying to load this into `chrome:://tracing` as-is just causes it to hang or crash. I would like to be able to `tail` the file to get the last x events but because all of the events are written on one line it is very hard to process.

The solution I have at the moment is to generate the trace file, split it with [jstream](https://github.com/bcicen/jstream) and then tail it for the events I want.

Ideally if there was an option to add newlines after every event I could skip this step and it would make the file much easier to work with in standard linux tools. Obviously this would increase the file size but 1 byte per event.

**Comment by thoren-d** [comment]
Thanks for the suggestion. Closing now that your PR is merged.
