### ISSUE TITLE
`RUSTSEC-2022-0081`: remove the `json` dependency

### ISSUE THREAD

**Issue by GrandChaman** [thoren-d/tracing-chrome#22]
As per the [security report](https://rustsec.org/advisories/RUSTSEC-2022-0081.html) by the RUSTSEC team.

This dependency ([`json`](https://crates.io/crates/json)) is unmaintained and probably should be removed.

Maybe, it could be replaced by [`serde_json`](https://crates.io/crates/serde_json) ?

**Comment by justinmoon** [comment]
Would it be possible to cut a new release containing this update?
